import { useState } from "react";
import AuthButtons from "../../components/auth/AuthButtons";
import GameScreen from "../../components/GameScreen/Screen";
import Inventory from "../../components/Inventory/Inventory";
import "./Game.css";

export type item = {
  name: string;
};

export type worldFlag = {
  name: string;
  state: boolean;
};

export default function Game() {
  // const allItems: item[] = [{ name: "key" }] as const;
  // Commented this out to make the linter happy for the CI on first demo; uncomment it when needed

  const [inventory, setInventory] = useState<item[]>([]);
  const [worldState, setWorldState] = useState<worldFlag[]>([]);
  const [selectedItem, setSelectedItem] = useState<string>("");

  const pickUpItem = (itemName: string) => {
    // Only add if inventory not full
    if (inventory.length < 5) {
      setInventory([...inventory, { name: itemName }]);
    }
  };

  const removeItem = (itemName: string) => {
    setInventory((prev) => {
      const idx = prev.findIndex((item) => item.name === itemName);
      if (idx === -1) return prev;
      const next = prev.slice();
      next.splice(idx, 1);
      return next;
    });
  };

  const toggleWorldFlag = (flagName: string) => {
    setWorldState((prev) => {
      // THIS WAS GENERATED BY AI. SURELY IT WORKS, RIGHT???
      const idx = prev.findIndex((f) => f.name === flagName);
      if (idx !== -1) {
        const next = prev.slice();
        const current = next[idx];
        next[idx] = { ...current, state: !current.state };
        return next;
      }
      return [...prev, { name: flagName, state: true }];
    });
  };

  const selectItem = (selectedItem: string) => {
    setSelectedItem(selectedItem);
  };

  return (
    <div className="game-screen">
      <div className="game-buttons">
        <AuthButtons />
      </div>
      <div className="game-window">
        <GameScreen
          inventory={inventory}
          onPickUpItem={pickUpItem}
          removeItem={removeItem}
          selectedItem={selectedItem}
          toggleWorldFlag={toggleWorldFlag}
          worldState={worldState}
        />
        <Inventory inventory={inventory} selectItem={selectItem} />
      </div>
    </div>
  );
}
