import { useState } from "react";
import AuthButtons from "../../components/auth/AuthButtons";
import GameScreen from "../../components/GameScreen/Screen";
import Inventory from "../../components/Inventory/Inventory";
import "./Game.css";
import { useAuth } from "../../components/auth/AuthProvider";

const BASE_URL = "https://four28-point-click-escape.onrender.com";

export type item = {
  name: string;
};

export type worldFlag = {
  name: string;
  state: boolean;
};

export default function Game() {
  // const allItems: item[] = [{ name: "key" }] as const;
  // Commented this out to make the linter happy for the CI on first demo; uncomment it when needed

  const [inventory, setInventory] = useState<item[]>([]);
  const [worldState, setWorldState] = useState<worldFlag[]>([]);
  const [selectedItem, setSelectedItem] = useState<string>("");
  const { user } = useAuth();

  const pickUpItem = (itemName: string) => {
    // Only add if inventory not full
    if (inventory.length < 5) {
      setInventory([...inventory, { name: itemName }]);
    }
  };

  const toggleWorldFlag = (flagName: string) => {
    setWorldState((prev) => {
      // THIS WAS GENERATED BY AI. SURELY IT WORKS, RIGHT???
      const idx = prev.findIndex((f) => f.name === flagName);
      if (idx !== -1) {
        const next = prev.slice();
        const current = next[idx];
        next[idx] = { ...current, state: !current.state };
        return next;
      }
      return [...prev, { name: flagName, state: true }];
    });
  };

  const selectItem = (selectedItem: string) => {
    setSelectedItem(selectedItem);
  };

  const saveGame = async (name: string, inventory: item[], worldState: worldFlag[]) => {
    const res = await fetch(`${BASE_URL}/game/save`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name, inventory, worldState }),
    });

    console.log("Username being sent: ", name)

    const data = await res.json();

    console.log("Response data:", data);

    if (!res.ok) {
      throw new Error(data.error || "Failed to save game");
    }

    return data;
  };

  return (
    <div className="game-screen">
      <div className="game-buttons">
        <button>Save</button>
        <AuthButtons />
        <button onClick={() => saveGame(user!.username, inventory, worldState)}>Save</button>
      </div>
      <div className="game-window">
        <GameScreen
          inventory={inventory}
          onPickUpItem={pickUpItem}
          selectedItem={selectedItem}
          toggleWorldFlag={toggleWorldFlag}
          worldState={worldState}
        />
        <Inventory inventory={inventory} selectItem={selectItem} />
      </div>
    </div>
  );
}
